# -*- coding: utf-8 -*-
"""greating.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pQzl2sSlIczTLFX58OQOrK_l-tCWc2pH
"""

import streamlit as st
st.title("Welcome to our premier site for using Streamlit. ")
name = st.text_input("what is your name")
if name:
    st.write("You've brightened up the site.", name, "Welcome")
    st.balloons()
