# -*- coding: utf-8 -*-
"""greating.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pQzl2sSlIczTLFX58OQOrK_l-tCWc2pH
"""

import streamlit as st
st.title("مرحيا بكم في مـوقـعنا الاول ياسـتخد ام ستريم ليت ")
name = st.text_input("ما هو اسمك")
if name:
    st.write("نورت الـمـوقع", name, "مرحيا بك ي")
    st.balloons()
